---
- name: use apache_vhost role playbook
  hosts: all
  become: true

  pre_tasks:
    - debug:
        msg: 'Beginning web server configuration.'

  roles:
    - apache2

  post_tasks:
    - debug:
        msg: 'Web server has been configured.'
